#!/usr/bin/env bash

source config

error_msg() {
  echo -e "\n${red}Usage:\n\t${scriptname} (f|farenheit|c|celcius) temperature-to-convert${nc}\n"
  echo -e "${green}Example:\n\t${scriptname} f 32${nc}"
  exit 99
}

scale_setup() {
  fc=("f" "c" "farenheit" "celcius")
  if [[ $(echo -e ${fc[@]} | grep -c $1) -eq 0 ]]; then
      error_msg
  else
      scale=$1
  fi
}

if [[ $# -gt 2 ]]; then
  echo -e "\n${red}Pleave provide 2 parameters only."
  error_msg
fi

#if [[ $# -lt 2 ]]; then
  
#fi

given_temperature="$2"

f2c() {
  temperature="$(echo -e "($given_temperature - 32) * 5/9" | bc)"
  echo -e "
  =======================
  | Farenheit to Celcius
  =======================
  | Farenheit\t: ${given_temperature}°F
  | Celcius\t: ${temperature}°C
  ======================="
}

c2f() {
  temperature="$(echo -e "($given_temperature * 9/5) + 32" | bc)"
  echo -e "
  =======================
  | Celcius to Farenheit
  =======================
  | Celcius\t: ${given_temperature}°C
  | Farenheit\t: ${temperature}°F
  ======================="
}

if [[ $# -lt 2 ]]; then
  error_msg
fi


case $1 in
  f) f2c ;;
  farenheit) f2c ;;
  c) c2f ;;
  celcius) c2f ;;
  *) error_msg ;;
esac
